
#  STAT 412/612
#  STRINGS  
  
library(tidyverse)
library(stringr)
library(dplyr)


#  PART 1

# What is a string ?
# A "string" is just a character variable that contains one or
# more characters. ... A character vector is a set of strings 
# stored as a single object. Most R functions that work on 
# character input are vectorised, i.e they will return the 
# appropriate value for each element in such a vector.

# The following are typical strings:

# Example 1  "a"
# Example 2  "abc"
# Example 3  "April"

# As stated, multiple strings are often stored in a character vector. 
# they can be generated by by using c( )

# Example 4

 c("nba" , "nfl" , "nhl", "mlb" , "ncaa")

# Note that strings have to be enclosed in quotes. If one is omitted,
# your output will feature a continuation character +.  Consider and
# try to run the following; (remove the # sound first)

  # BernieSanders"

# Did you not get the continuation character + ?

# Now run the following:  This is correct string notation.

"BernieSanders"


# Strings can be created using either single quotes or double quotes.
# Preferably, most use double quotes, " ". If, however, you wish to 
# create a string within a string single quotes should also be used.

# Example 5  
 "Yesterday John said 'I am happy' over and over again"

# To include a literal single or double quote in a string,
# you will have to "escape" it with a forward slash.  \

#Example 6   I want the content of my string to reflect the 
# following,  ", ', or \ .  To show the content of my string,
# I must use the command  witeLines

# Solution

writeLines("\"")

writeLines("\'")

writeLines("\\")




# Note that we did output  " , ' and \.
.
# Example 7  I now want the content of my string to reflect the
# following, \abc

# Solution

writeLines("\\abc")

# Example 8

# Let's consider the following vector assignment.
x<- c("\"" , "\\")
x

# What elements do you think will be "escaped' ?

# Again, we will find out by using writeLines.

writeLines(x)

# If your answers were  "  and  \  you were correct !!  Good Job

# Finally, let's consider the vector again on line 27,

c("nba" , "nfl" , "nhl", "mlb" , "ncaa")

# If we run this without writeLines we get the double quoted notation again.

# You must use the writeLines command to get the desired content of
# the collection of strings (without the double quotes)
writeLines(c("nba" , "nfl" , "nhl", "mlb" , "ncaa"))


# String Length  
# We will use the stringr function str_length() to determine the 
# length of a string.

# Example 9
# Use r coding to confirm that the string "abcde" has a length of 5.

# Solution
str_length("abcde")

# Example 10
# Use r coding to confirm that the string "abc de" has a length of
# 6.

# Solution
str_length("abc de")


# Example 10
# Use r coding to confirm that the vector collection of strings 
# c("a","ab", "abc") have lengths of 1 , 2 , and 3.

# Solution
str_length(c("a","ab", "abc"))

# Combining Strings
# In order to combine strings, we will use the stringr function
#str_c()

# Example 11   Use r coding to combine the strings "a"  and "bc"

str_c("a" , "bc")

# Example 12  Use r coding to combine the strings "n" , "f", "l"

str_c('n' , "f" , "l")

# You can also determine how the elements are separated by using a
# sep argument as follows;

str_c("n" , "f" , "l" , sep = " ")

# Example 13  Use r coding to combine the strings "ford" and the 
# vector c("a" ' "b")

str_c("ford" , c("a","b"))

#  And now remove the double quotes

writeLines(str_c("ford" , c("a","b")))

# Collapsing Strings   
# To collapse a collection of strings into a single string, use 
# collapse.

# Example 14
str_c(c("ab" , "cd", "ef") , collapse = "")

# Note that you have one string instead of a collection of three strings


# Sub-setting Strings
# We can use the function str_sub() to extract parts of a string.

# We will use the following vector of strings to illustrate some
# sub-setting procedures.

y<- c("abcd" , "efghi")
y

# str_sub(x, 1,3)   (For each string, start with the first element
# and end with the third element . Include all elements in between)

str_sub(y, 1,3)

# str_sub(x, 2,4)    (For each string, start with the second element
# and end with the fourth element. Include all elements in between)

str_sub(y, 2,4)


# We can also change text to upper case or lower case by using 
# str_to_lower or str_to_upper

# str_to_upper(str_sub(x,1,2))  (We will change the first element and
# the second element of each string to upper case letters)

z<- c("abcd" , "efghi")
z

str_to_upper(str_sub(z,1,2))

# What will the following code output?

str_to_upper(str_sub(z))


# PART 2

# Matching  Patterns with Regular Expressions

# Basic Matches (Use the function str_view to force Basic Matches)

# Example 15 (For the vector of strings assigned x, force a match
# for   an)

install.packages("htmlwidgets")
library(htmlwidgets)

  X<- c("apple", "banana", "pear")
  X
  str_view(X, "an")
  
# Examples 16-18 (In this example the use of periods placed before 
# and after a character, will match any character, except a newline)
 
  X<- c("apple", "banana", "pear")
  X
  
  str_view(X , ".a.")
  
  str_view("bonanza" , ".z.")
  
  str_view("bonanza" , ".on.")
  
# Anchors (A regular expression can be anchored , so that it 
# matches the start or the end of a string.)  Use  ^ to match the
# start and use $ to match the end)

# Example 19 (The following code will force matches if the starting
# character of a string is  M)
  str_view(c("Minnesota" ,"Kansas" , "Maine") , "^M")
  
# Example 20 (The following code will force matches if the ending
# character of a string is s)
  str_view(c("Minnesota" ,"Kansas" , "Maine") , "s$")

# To match an entire string, use ^ and $
# Example 21 (The following code will force a match for a full string
# )

  str_view(c("Minnesota" ,"Kansas" , "Maine") , "^Kansas$")

# For another string application we will use the corpus of common
# words.  (Run the following code to produce the matrix of words)

stringr ::  words

# Example 22  (Create a regular expression that will find words that
# start with p)

str_subset(words, "^p")

# Example 23  (Create a regular expression that will find words that
# end with p)

str_subset(words, "p$")


# Example 24  (Create regular expressions that will find words that
# start with p or a b)

str_subset(words, "^[p|b]")


# Example 25  (Create regular expressions that finds  all
# words that end with "ing") Note the use of parentheses

str_subset(words, "(ing)$")

# Example 26  (Create regular expressions that find all
# words that have exactly 10 characters) 
# Note the use of periods)

str_subset(words, "^..........$")

# Example 27  (Create regular expressions that find all
# words that have 10 or more characters) 
# Note the use of periods)

str_subset(words, "..........")


# Example 28  (Create regular expressions that find all
# four letter words that end in t

str_subset(words, "^...t$")


str_subset(words, "^s.....$")


# Example 29  (Create regular expressions that find all
# words that start with mo and end with y.  i.e.  monday


str_subset(words, "^mo") -> z
z

str_subset(z, "y$") 


# Example 30  (Create regular expressions that find all
# words that end in t or s)

str_subset(words,  "[t|s]$")


# Example 31  (Create regular expressions that find all
# words that end in st)

str_subset(words,  "(st)$")


# Example 31  (Create regular expressions that find all
# words that end in st or ct)

# method 1

str_subset(words,  "[sc]t$") # Did not work !!


# method 2
str_subset(words,  "(ct)$") -> x
x

str_subset(words,  "(st)$") -> y
y

union(x,y)     # This works !!



q()
y
